### ISSUE TITLE
bash: line 1: 404:: command not found

### ISSUE THREAD

**Issue by Eric-sson** [ImKKingshuk/BloatwareHatao#1]
I am getting the below error when I want to run the script with command bash BloatwareHatao.sh

Fetching bloatware removal script from xiaomi for xiaomi/oneui-1.sh (Ultra)...
bash: line 1: 404:: command not found
Bloatware removal completed.

I am using Ubuntu 22.04
Any idea what is causing this?

**Comment by mastercuber55** [comment]
you need this 

https://developer.android.com/tools/releases/platform-tools

**Comment by ImKKingshuk** [comment]
Make sure you setup your device properly, here the latest requirements to run the tool.

## Requirements

- macOS, Linux, Windows
- Bash-compatible environment.
- Internet connectivity for fetching manufacturer-specific bloatware removal scripts.
- Android Device with [ADB (Android Debug Bridge)](https://developer.android.com/tools/adb) Enabled
- [Android SDK Platform-Tools](https://developer.android.com/tools/releases/platform-tools) installed properly and added to your system's PATH.
